
omniauth:
  facebook_key: "1428822157336759"
  facebook_secret: "b8e47bb7a59e81360eff3ed897e0199c"
  linkedin_key: "31azcdigi8tt"
  linkedin_secret: "OKd1hmuJoNOg9J2g"
  google_oauth2_key: "928801233183"
  google_oauth2_secret: "-nMQ0dEfcaBITxzwYHZPQ3v-"

email:
  user_name: "samuels410"
  password: "samuels_253325"
  domain: "life-donors.org"
  address: "smtp.sendgrid.net"
  port: 587
