
omniauth:
  facebook_key: "718010624878712"
  facebook_secret: "9e4d73100337be29a836d0b44c446c0b"
  linkedin_key: "31azcdigi8tt"
  linkedin_secret: "OKd1hmuJoNOg9J2g"
  google_oauth2_key: "928801233183"
  google_oauth2_secret: "-nMQ0dEfcaBITxzwYHZPQ3v-"

email:
  user_name: "lifedonor.org"
  password: "samuels_253325"
  domain: "helpalife.in"
  address: "smtp.gmail.com"
  port: 587

domain_name: "helpalife.in"
twitter_url: ""
youtube_url: ""
facebook_url: ""
google_plus_url: ""
linked_in_url: ""